version: 2.1

executors:
  unity-webgl-executor:
    docker:
      - image: unityci/editor:2022.3.7f1-webgl-0

orbs:
  aws-s3: circleci/aws-s3@3.1

jobs:
  activate-license:
    executor: unity-webgl-executor
    steps:
      - checkout
      - run:
          name: Activate Unity license
          command: |
            echo $UNITY_ENCODED_LICENSE | base64 --decode > Unity_v2022.3.7f1.ulf
            unity-editor -logFile /dev/stdout -quit -batchmode -nographics -manualLicenseFile Unity_v2022.3.7f1.ulf
      - run:
          name: Check Unity license activation
          command: |
            cat /root/.local/share/unity3d/Unity/Unity_lic.ulf

  build:
    executor: unity-webgl-executor
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            echo "Preparing environment..."
            echo $UNITY_ENCODED_LICENSE | base64 --decode > Unity_v2022.3.7f1.ulf
      - run:
          name: Build Unity project
          command: |
            unity-editor -logFile /dev/stdout -quit -batchmode -nographics -projectPath src -buildTarget WebGL -executeMethod BuildScript.Build
      - persist_to_workspace:
          root: .
          paths:
            - src/Builds/WebGL

  deploy:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-s3/sync:
          aws-region: $AWS_REGION
          role-arn: $AWS_ROLE_ARN
          from: src/Builds/WebGL/WebGL
          to: s3://unity-aws-deploy

workflows:
  build-unity-project:
    jobs:
      - activate-license:
          context: Unity-context
      - build:
          requires:
            - activate-license
          context: Unity-context
      - deploy:
          requires:
            - build
          context: Unity-context
