version: 2.1

orbs:
  unity: game-ci/unity@1.4.0
  aws-s3: circleci/aws-s3@3.1

jobs:
  create-activation-file:
    docker:
      - image: game-ci/unity:2022.3.7f1
    steps:
      - checkout
      - unity/create-activation-file:
          editor_version: 2022.3.7f1
      - store_artifacts:
          path: Unity_v2022.3.7f1.alf
          destination: Unity_v2022.3.7f1.alf

  build:
    executor:
      name: "unity/ubuntu"
      target_platform: "webgl"
      editor_version: "2022.3.7f1"
      resource_class: "large"
    steps:
      - checkout
      - unity/activate:
          license-file-path: ./Unity_v2022.3.7f1.ulf
      - unity/prepare-env:
          unity-license-var-name: "UNITY_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
      - unity/build:
          project-path: "src"
          build-target: "WebGL"
          compress: false
          store-artifacts: false
      - persist_to_workspace:
          root: .
          paths:
            - "src/Builds/WebGL"

  deploy:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-s3/sync:
          aws-region: $AWS_REGION
          role-arn: $AWS_ROLE_ARN
          from: "src/Builds/WebGL"
          to: 's3://unity-aws-deploy'

workflows:
  create-unity-activation-file:
    jobs:
      - create-activation-file

  build-and-deploy:
    jobs:
      - build:
          requires:
            - create-activation-file
          context: unity
      - deploy:
          requires:
            - build
          context: aws
