version: 2.1

orbs:
  unity: game-ci/unity@1.4.0
  aws-s3: circleci/aws-s3@3.1

jobs:
  activate-license:
    docker:
      - image: unityci/editor:2022.3.7f1-webgl-0
    steps:
      - checkout
      - run:
          name: Activate Unity license
          command: |
            unity-editor -logFile /dev/stdout -quit -batchmode -nographics -manualLicenseFile /path/to/your/license/file.ulf
      - run:
          name: Check Unity license activation
          command: |
            cat /root/.local/share/unity3d/Unity/Unity_lic.ulf

  build:
    executor:
      name: "unity/ubuntu"
      target_platform: "webgl"
      editor_version: "2022.3.7f1"
      resource_class: "large"
    steps:
      - checkout
      - unity/prepare-env:
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
      - unity/build:
          project-path: "src"
          build-target: "WebGL"
          compress: false
          store-artifacts: false
      - persist_to_workspace:
          root: .
          paths:
            - "src/Builds/WebGL"

  deploy:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-s3/sync:
          aws-region: AWS_REGION
          role-arn: $AWS_ROLE_ARN
          from: "src/Builds/WebGL/WebGL"
          to: 's3:::unity-aws-deploy'

workflows:
  build-unity-project:
    jobs:
      - activate-license:
          context: Unity-context
      - build:
          requires:
            - activate-license
          context: Unity-context
      - deploy:
          requires: 
            - build
          context: Unity-context
